### ISSUE TITLE
pkg_resources.DistributionNotFound: The 'dirsync' distribution was not found and is required by wheel2deb

### ISSUE THREAD

**Issue by smijolovic** [upciti/wheel2deb#18]
Running the command: wheel2deb --map attrs=attr

Is producing the following output:

Traceback (most recent call last):
  File "/usr/bin/wheel2deb", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3254, in <module>
    def _initialize_master_working_set():
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3237, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3266, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 584, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 901, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 787, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'dirsync' distribution was not found and is required by wheel2deb

**Comment by smijolovic** [comment]
Figured this out.  Had to build dirsync from source, because we don't use pip to install packages - we use deb packaging.

Build debian package for dirsync here: https://github.com/tkhyn/dirsync

Might be something to include in the README file about the dependency on dirsync.
